INSERT INTO evolve VALUES ('1','Null','0');
INSERT INTO evolve VALUES ('2','Lv. 16','1');
INSERT INTO evolve VALUES ('3','Lv. 32','2');
INSERT INTO evolve VALUES ('4','Null','0');
INSERT INTO evolve VALUES ('5','Lv. 16','4');
INSERT INTO evolve VALUES ('6','Lv. 36','5');
INSERT INTO evolve VALUES ('7','Null','0');
INSERT INTO evolve VALUES ('8','Lv. 16','7');
INSERT INTO evolve VALUES ('9','Lv. 36','8');
INSERT INTO evolve VALUES ('10','Null','0');
INSERT INTO evolve VALUES ('11','Lv. 7','10');
INSERT INTO evolve VALUES ('12','Lv. 10','11');
INSERT INTO evolve VALUES ('13','Null','0');
INSERT INTO evolve VALUES ('14','Lv. 7','13');
INSERT INTO evolve VALUES ('15','Lv. 10','14');
INSERT INTO evolve VALUES ('16','Null','0');
INSERT INTO evolve VALUES ('17','Lv. 18','16');
INSERT INTO evolve VALUES ('18','Lv. 36','17');
INSERT INTO evolve VALUES ('19','Null','0');
INSERT INTO evolve VALUES ('20','Lv. 20','19');
INSERT INTO evolve VALUES ('21','Null','0');
INSERT INTO evolve VALUES ('22','Lv. 20','21');
INSERT INTO evolve VALUES ('23','Null','0');
INSERT INTO evolve VALUES ('24','Lv. 22','23');
INSERT INTO evolve VALUES ('25','Null','0');
INSERT INTO evolve VALUES ('26','Thunderstone','25');
INSERT INTO evolve VALUES ('27','Null','0');
INSERT INTO evolve VALUES ('28','Lv. 22','27');
INSERT INTO evolve VALUES ('29','Null','0');
INSERT INTO evolve VALUES ('30','Lv. 16','29');
INSERT INTO evolve VALUES ('31','Moon Stone','30');
INSERT INTO evolve VALUES ('32','Null','0');
INSERT INTO evolve VALUES ('33','Lv. 16','32');
INSERT INTO evolve VALUES ('34','Moon Stone','33');
INSERT INTO evolve VALUES ('35','Null','0');
INSERT INTO evolve VALUES ('36','Moon Stone','35');
INSERT INTO evolve VALUES ('37','Null','0');
INSERT INTO evolve VALUES ('38','Fire Stone','37');
INSERT INTO evolve VALUES ('39','Null','0');
INSERT INTO evolve VALUES ('40','Moon Stone','39');
INSERT INTO evolve VALUES ('41','Null','0');
INSERT INTO evolve VALUES ('42','Lv. 22','41');
INSERT INTO evolve VALUES ('43','Null','0');
INSERT INTO evolve VALUES ('44','Lv. 22','43');
INSERT INTO evolve VALUES ('45','Leaf Stone','44');
INSERT INTO evolve VALUES ('46','Null','0');
INSERT INTO evolve VALUES ('47','Lv. 24','46');
INSERT INTO evolve VALUES ('48','Null','0');
INSERT INTO evolve VALUES ('49','Lv. 31','48');
INSERT INTO evolve VALUES ('50','Null','0');
INSERT INTO evolve VALUES ('51','Lv. 26','50');
INSERT INTO evolve VALUES ('52','Null','0');
INSERT INTO evolve VALUES ('53','Lv. 28','52');
INSERT INTO evolve VALUES ('54','Null','0');
INSERT INTO evolve VALUES ('55','Lv. 33','54');
INSERT INTO evolve VALUES ('56','Null','0');
INSERT INTO evolve VALUES ('57','Lv. 28','56');
INSERT INTO evolve VALUES ('58','Null','0');
INSERT INTO evolve VALUES ('59','Fire Stone','58');
INSERT INTO evolve VALUES ('60','Null','0');
INSERT INTO evolve VALUES ('61','Lv. 25','60');
INSERT INTO evolve VALUES ('62','Water Stone','61');
INSERT INTO evolve VALUES ('63','Null','0');
INSERT INTO evolve VALUES ('64','Lv. 16','63');
INSERT INTO evolve VALUES ('65','Trade','64');
INSERT INTO evolve VALUES ('66','Null','0');
INSERT INTO evolve VALUES ('67','Lv. 28','66');
INSERT INTO evolve VALUES ('68','Trade','67');
INSERT INTO evolve VALUES ('69','Null','0');
INSERT INTO evolve VALUES ('70','Lv. 21','69');
INSERT INTO evolve VALUES ('71','Leaf Stone','70');
INSERT INTO evolve VALUES ('72','Null','0');
INSERT INTO evolve VALUES ('73','Lv. 30','72');
INSERT INTO evolve VALUES ('74','Null','0');
INSERT INTO evolve VALUES ('75','Lv. 25','74');
INSERT INTO evolve VALUES ('76','Trade','75');
INSERT INTO evolve VALUES ('77','Null','0');
INSERT INTO evolve VALUES ('78','Lv. 40','77');
INSERT INTO evolve VALUES ('79','Null','0');
INSERT INTO evolve VALUES ('80','Lv. 37','79');
INSERT INTO evolve VALUES ('81','Null','0');
INSERT INTO evolve VALUES ('82','Lv. 30','81');
INSERT INTO evolve VALUES ('83','Null','0');
INSERT INTO evolve VALUES ('84','Null','0');
INSERT INTO evolve VALUES ('85','Lv. 31','84');
INSERT INTO evolve VALUES ('86','Null','0');
INSERT INTO evolve VALUES ('87','Lv. 34','86');
INSERT INTO evolve VALUES ('88','Null','0');
INSERT INTO evolve VALUES ('89','Lv. 38','88');
INSERT INTO evolve VALUES ('90','Null','0');
INSERT INTO evolve VALUES ('91','Water Stone','90');
INSERT INTO evolve VALUES ('92','Null','0');
INSERT INTO evolve VALUES ('93','Lv. 25','92');
INSERT INTO evolve VALUES ('94','Trade','93');
INSERT INTO evolve VALUES ('95','Null','0');
INSERT INTO evolve VALUES ('96','Null','0');
INSERT INTO evolve VALUES ('97','Lv. 26','96');
INSERT INTO evolve VALUES ('98','Null','0');
INSERT INTO evolve VALUES ('99','Lv. 28','98');
INSERT INTO evolve VALUES ('100','Null','0');
INSERT INTO evolve VALUES ('101','Lv. 30','100');
INSERT INTO evolve VALUES ('102','Null','0');
INSERT INTO evolve VALUES ('103','Leaf Stone','102');
INSERT INTO evolve VALUES ('104','Null','0');
INSERT INTO evolve VALUES ('105','Lv. 28','104');
INSERT INTO evolve VALUES ('106','Null','0');
INSERT INTO evolve VALUES ('107','Null','0');
INSERT INTO evolve VALUES ('108','Null','0');
INSERT INTO evolve VALUES ('109','Null','0');
INSERT INTO evolve VALUES ('110','Lv. 35','109');
INSERT INTO evolve VALUES ('111','Null','0');
INSERT INTO evolve VALUES ('112','Lv. 42','111');
INSERT INTO evolve VALUES ('113','Null','0');
INSERT INTO evolve VALUES ('114','Null','0');
INSERT INTO evolve VALUES ('115','Null','0');
INSERT INTO evolve VALUES ('116','Null','0');
INSERT INTO evolve VALUES ('117','Lv. 32','116');
INSERT INTO evolve VALUES ('118','Null','0');
INSERT INTO evolve VALUES ('119','Lv. 33','118');
INSERT INTO evolve VALUES ('120','Null','0');
INSERT INTO evolve VALUES ('121','Water Stone','120');
INSERT INTO evolve VALUES ('122','Null','0');
INSERT INTO evolve VALUES ('123','Null','0');
INSERT INTO evolve VALUES ('124','Null','0');
INSERT INTO evolve VALUES ('125','Null','0');
INSERT INTO evolve VALUES ('126','Null','0');
INSERT INTO evolve VALUES ('127','Null','0');
INSERT INTO evolve VALUES ('128','Null','0');
INSERT INTO evolve VALUES ('129','Null','0');
INSERT INTO evolve VALUES ('130','Lv. 20','129');
INSERT INTO evolve VALUES ('131','Null','0');
INSERT INTO evolve VALUES ('132','Null','0');
INSERT INTO evolve VALUES ('133','Null','0');
INSERT INTO evolve VALUES ('134','Water Stone','133');
INSERT INTO evolve VALUES ('135','Thunderstone','133');
INSERT INTO evolve VALUES ('136','Fire Stone','133');
INSERT INTO evolve VALUES ('137','Null','0');
INSERT INTO evolve VALUES ('138','Null','0');
INSERT INTO evolve VALUES ('139','Lv. 40','138');
INSERT INTO evolve VALUES ('140','Null','0');
INSERT INTO evolve VALUES ('141','Lv. 40','140');
INSERT INTO evolve VALUES ('142','Null','0');
INSERT INTO evolve VALUES ('143','Null','0');
INSERT INTO evolve VALUES ('144','Null','0');
INSERT INTO evolve VALUES ('145','Null','0');
INSERT INTO evolve VALUES ('146','Null','0');
INSERT INTO evolve VALUES ('147','Null','0');
INSERT INTO evolve VALUES ('148','Lv. 30','147');
INSERT INTO evolve VALUES ('149','Lv. 55','148');
INSERT INTO evolve VALUES ('150','Null','0');
INSERT INTO evolve VALUES ('151','Null','0');
