INSERT INTO item_loc VALUES ('IID','LName');
INSERT INTO item_loc VALUES ('ANTIDOTE','PokeMart, Virdian Forest');
INSERT INTO item_loc VALUES ('AWAKENING','PokeMart, Pokemon Tower');
INSERT INTO item_loc VALUES ('BICYCLE','Cerulean City');
INSERT INTO item_loc VALUES ('BIKE VOUCHER','Vermilion City');
INSERT INTO item_loc VALUES ('BURN HEAL','PokeMart');
INSERT INTO item_loc VALUES ('CALCIUM','Silph Co., Route 13, Pokemon Mansion, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('CARBOS','Silph Co.,Safari Zone, Power Plant, Pokemon Mansion, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('CARD KEY','Silph Co.');
INSERT INTO item_loc VALUES ('COIN','Casino');
INSERT INTO item_loc VALUES ('COIN CASE','Celadon City');
INSERT INTO item_loc VALUES ('DIRE HIT','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('DOME FOSSIL','Mt. Moon');
INSERT INTO item_loc VALUES ('ELIXER','Pokemon Tower');
INSERT INTO item_loc VALUES ('ESCAPE ROPE','PokeMart, Mt. Moon, Casino, Pokemon Tower, Silph Co., Pokemon Mansion');
INSERT INTO item_loc VALUES ('ETHER','S. S. Anne');
INSERT INTO item_loc VALUES ('EXP. ALL','Route 15');
INSERT INTO item_loc VALUES ('FIRE STONE','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('FRESH WATER','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('FULL HEAL','PokeMart Silph Co., Victory Road');
INSERT INTO item_loc VALUES ('FULL RESTORE','PokeMart, Safari Zone, Pokemon Mansion, Cerulean Cave');
INSERT INTO item_loc VALUES ('GOLD TEETH','Safari Zone');
INSERT INTO item_loc VALUES ('GOOD ROD','Fuchsia City');
INSERT INTO item_loc VALUES ('GREAT BALL','PokeMart, S. S. Anne');
INSERT INTO item_loc VALUES ('GUARD SPEC.','Celadon Dept. Store, Victory Road');
INSERT INTO item_loc VALUES ('HELIX FOSSIL','Mt. Moon');
INSERT INTO item_loc VALUES ('HP UP','Route 2, Mt. Moon, Casino, Celadon Dept. Store, Pokemon Tower, Silph Co., Power Plant');
INSERT INTO item_loc VALUES ('HYPER POTION','PokeMart, Casino, Silph Co.');
INSERT INTO item_loc VALUES ('ICE HEAL','PokeMart');
INSERT INTO item_loc VALUES ('IRON','Casino, Route 12, Pokemon Mansion, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('ITEM FINDER','Route 11');
INSERT INTO item_loc VALUES ('LEAF STONE','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('LEMONADE','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('LIFT KEY','Casino');
INSERT INTO item_loc VALUES ('MASTER BALL','Silph Co.');
INSERT INTO item_loc VALUES ('MAX ELIXER','Cerulean Cave');
INSERT INTO item_loc VALUES ('MAX ETHER','S. S. Anne');
INSERT INTO item_loc VALUES ('MAX POTION','PokeMart, S. S. Anne, Safari Zone, Pokemon Mansion');
INSERT INTO item_loc VALUES ('MAX REPEL','PokeMart');
INSERT INTO item_loc VALUES ('MAX REVIVE','Silph Co., Safari Zone, Victory Road, Cerulean Cave');
INSERT INTO item_loc VALUES ('MOON STONE','Mt. Moon, Route 2, Casino, Pokemon Mansion');
INSERT INTO item_loc VALUES ('NUGGET','Casino, Pokemon Tower, Safari Zone, Cerulean Cave');
INSERT INTO item_loc VALUES ('OAK PARCEL','Virdian City, PokeMart');
INSERT INTO item_loc VALUES ('OLD AMBER','Pewter City');
INSERT INTO item_loc VALUES ('OLD ROD','Vermilion City');
INSERT INTO item_loc VALUES ('PARALYZE HEAL','PokeMart');
INSERT INTO item_loc VALUES ('POKeBALL','PokeMart, Viridian Forest');
INSERT INTO item_loc VALUES ('POKeDEX','Pallet Town');
INSERT INTO item_loc VALUES ('POKeDOLL','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('POKeFLUTE','Pokemon Tower');
INSERT INTO item_loc VALUES ('POTION','PokeMart, Pallet Town, Route 1, Viridian City, Viridian Forest, Mt. Moon');
INSERT INTO item_loc VALUES ('PP UP','Cerulean Cave');
INSERT INTO item_loc VALUES ('PROTEIN','Celadon Dept. Store, Silph Co., Route 13, Safari Zone');
INSERT INTO item_loc VALUES ('RARE CANDY','Mt. Moon, Cerulean City, S. S. Anne, Casino, Pokemon Tower, Silph Co., Power Plant, Pokemon Mansion, Victory Road, Cerulean Cave');
INSERT INTO item_loc VALUES ('REPEL','PokeMart');
INSERT INTO item_loc VALUES ('REVIVE','PokeMart');
INSERT INTO item_loc VALUES ('S.S. TICKET','Cerulean City');
INSERT INTO item_loc VALUES ('SAFARI BALL (30)','Safari Zone');
INSERT INTO item_loc VALUES ('SECRET KEY','Pokemon Mansion');
INSERT INTO item_loc VALUES ('SILPH SCOPE','Casino');
INSERT INTO item_loc VALUES ('SODA POP','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('SUPER POTION','PokeMart, Casino');
INSERT INTO item_loc VALUES ('SUPER REPEL','PokeMart');
INSERT INTO item_loc VALUES ('SUPER ROD','Route 12');
INSERT INTO item_loc VALUES ('THUNDER STONE','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TOWN MAP','Pallet Town');
INSERT INTO item_loc VALUES ('ULTRA BALL','PokeMart, Cerulean Cave');
INSERT INTO item_loc VALUES ('WATER STONE','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('X ACCURACY','Pokemon Tower, Silph Co., Celadon Dept. Store');
INSERT INTO item_loc VALUES ('X ATTACK','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('X DEFEND','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('X SPECIAL','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('X SPEED','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM01','Mt. Moon, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM02','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM03','Saffron City');
INSERT INTO item_loc VALUES ('TM04','Route 4');
INSERT INTO item_loc VALUES ('TM05','Victory Road, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM06','Fuchsia City');
INSERT INTO item_loc VALUES ('TM07','Celadon Dept. Store, Casino');
INSERT INTO item_loc VALUES ('TM08','Vermilion City, S. S. Anne');
INSERT INTO item_loc VALUES ('TM09','Saffron City, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM10','Casino');
INSERT INTO item_loc VALUES ('TM11','Cerulean City');
INSERT INTO item_loc VALUES ('TM12','Mt. Moon');
INSERT INTO item_loc VALUES ('TM13','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM14','Cinnabar Island, Pokemon Mansion');
INSERT INTO item_loc VALUES ('TM15','Celadon City');
INSERT INTO item_loc VALUES ('TM16','Route 12');
INSERT INTO item_loc VALUES ('TM17','Victory Road, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM18','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM19','Route 25');
INSERT INTO item_loc VALUES ('TM20','Route 15');
INSERT INTO item_loc VALUES ('TM21','Celadon City');
INSERT INTO item_loc VALUES ('TM22','Cinnabar Island, Pokemon Mansion');
INSERT INTO item_loc VALUES ('TM23','Celadon City');
INSERT INTO item_loc VALUES ('TM24','Vermilion Gym');
INSERT INTO item_loc VALUES ('TM25','Power Plant');
INSERT INTO item_loc VALUES ('TM26','Saffron City');
INSERT INTO item_loc VALUES ('TM27','Viridian City');
INSERT INTO item_loc VALUES ('TM28','Cerulean City');
INSERT INTO item_loc VALUES ('TM29','Saffron City');
INSERT INTO item_loc VALUES ('TM30','Route 9');
INSERT INTO item_loc VALUES ('TM31','Saffron City');
INSERT INTO item_loc VALUES ('TM32','Fuchsia City, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM33','Power Plant, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM34','Pewter City');
INSERT INTO item_loc VALUES ('TM35','Cinnabar Island');
INSERT INTO item_loc VALUES ('TM36','Saffron City');
INSERT INTO item_loc VALUES ('TM37','Fuchsia City, Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM38','Cinnabar Island');
INSERT INTO item_loc VALUES ('TM39','Route 12');
INSERT INTO item_loc VALUES ('TM40','Fuchsia City');
INSERT INTO item_loc VALUES ('TM41','Celadon City');
INSERT INTO item_loc VALUES ('TM42','Viridian City');
INSERT INTO item_loc VALUES ('TM43','Victory Road');
INSERT INTO item_loc VALUES ('TM44','Vermilion City');
INSERT INTO item_loc VALUES ('TM45','Route 24');
INSERT INTO item_loc VALUES ('TM46','Saffron City');
INSERT INTO item_loc VALUES ('TM47','Victory Road');
INSERT INTO item_loc VALUES ('TM48','Celadon Dept. Store');
INSERT INTO item_loc VALUES ('TM49','Celadon Dept. Store Roof');
INSERT INTO item_loc VALUES ('TM50','Celadon City ');
INSERT INTO item_loc VALUES ('HM01','S. S. Anne');
INSERT INTO item_loc VALUES ('HM02','Route 16');
INSERT INTO item_loc VALUES ('HM03','Fuchsia City');
INSERT INTO item_loc VALUES ('HM04','Fuchsia City');
INSERT INTO item_loc VALUES ('HM05','Route 2');
