INSERT INTO item VALUES ('Antidote','Recovery','Cures poison');
INSERT INTO item VALUES ('Awakening','Recovery','Cures sleep');
INSERT INTO item VALUES ('Bicycle','Key','Allows you to travel faster');
INSERT INTO item VALUES ('Bike Voucher','Key','Used to get a FREE Bike');
INSERT INTO item VALUES ('Burn Heal','Recovery','Heals burns');
INSERT INTO item VALUES ('Calcium','Vitamins','Increases Special level');
INSERT INTO item VALUES ('Carbos','Vitamins','Increases Speed level');
INSERT INTO item VALUES ('Card Key','Key','Unlocks Silph Co. doors');
INSERT INTO item VALUES ('Coin','Miscellaneous','Slot Machine money');
INSERT INTO item VALUES ('Coin Case','Key','Holds coins');
INSERT INTO item VALUES ('Dire Hit','Battle','Increases attack effectiveness');
INSERT INTO item VALUES ('Dome Fossil','Miscellaneous','Changes into Kabuto');
INSERT INTO item VALUES ('Elixir','Recovery','Gives 10 PP to all Attacks');
INSERT INTO item VALUES ('Escape Rope','Miscellaneous','Used to escape an area');
INSERT INTO item VALUES ('Ether','Recovery','Gives 10 PP to one Ability');
INSERT INTO item VALUES ('Exp. Share','Key','Shares experience points');
INSERT INTO item VALUES ('Fire Stone','Stone','Evolves some Fire Pokemon');
INSERT INTO item VALUES ('Fresh Water','Recovery','Quenches thirsts Restores 50 HP');
INSERT INTO item VALUES ('Full Heal','Recovery','Cures any ailments');
INSERT INTO item VALUES ('Full Restore','Recovery','Cures any ailments Restores all HP');
INSERT INTO item VALUES ('Gold Teeth','Key','Helps Warden to Speak');
INSERT INTO item VALUES ('Good Rod','Key','Used to fish');
INSERT INTO item VALUES ('Great Ball','Ball','More Effective than a Pokeball');
INSERT INTO item VALUES ('Guard Spec.','Battle','Disables Special Attacks');
INSERT INTO item VALUES ('Helix Fossil','Miscellaneous','Changes into Omanyte');
INSERT INTO item VALUES ('HP Up','Vitamins','Increases HP by 1');
INSERT INTO item VALUES ('Hyper Potion','Recovery','Restores 200 HP');
INSERT INTO item VALUES ('Ice Heal','Recovery','Heals frozen Pokemon');
INSERT INTO item VALUES ('Iron','Vitamins','Increases Defense level');
INSERT INTO item VALUES ('Itemfinder','Key','Finds Hidden Items');
INSERT INTO item VALUES ('Leaf Stone','Stone','Evolves some Grass Pokemon');
INSERT INTO item VALUES ('Lemonade','Recovery','Quenches thirst Restores 80 HP');
INSERT INTO item VALUES ('Lift Key','Key','Activates Game Corner Elevator');
INSERT INTO item VALUES ('Master Ball','Ball','Catches Pokemon 100% of time');
INSERT INTO item VALUES ('Max Elixir','Recovery','Restores all PP');
INSERT INTO item VALUES ('Max Ether','Recovery','Restores all PP of 1 ability');
INSERT INTO item VALUES ('Max Potion','Recovery','Restores all HP');
INSERT INTO item VALUES ('Max Repel','Miscellaneous','Prevents wild Pokemon from attacking');
INSERT INTO item VALUES ('Max Revive','Recovery','Revives Restores all HP');
INSERT INTO item VALUES ('Moon Stone','Stone','Evolves some Pokemon');
INSERT INTO item VALUES ('Nugget','Miscellaneous','Sold for 5000');
INSERT INTO item VALUES ('Oaks Parcel','Key','Exchange for Pokedex');
INSERT INTO item VALUES ('Old Amber','Miscellaneous','Changes into Aerodactyl');
INSERT INTO item VALUES ('Old Rod','Key','Fish for Magicarp');
INSERT INTO item VALUES ('Parlyz Heal','Recovery','Heals Paralysis');
INSERT INTO item VALUES ('Poke Ball','Ball','Lowest odds of catching Pokemon');
INSERT INTO item VALUES ('Poke Doll','Miscellaneous','Distracts Opponents Makes girls happy');
INSERT INTO item VALUES ('Poke Flute','Key','Wakes sleeping Pokemon');
INSERT INTO item VALUES ('Pokedex','Key','Records Pokemon Data');
INSERT INTO item VALUES ('Potion','Recovery','Restores 20 HP');
INSERT INTO item VALUES ('PP Up*','Vitamins','Increases PP by 1');
INSERT INTO item VALUES ('Protein','Vitamins','Increases Attack level');
INSERT INTO item VALUES ('Rare Candy','Vitamins','Increases Exp Level by 1');
INSERT INTO item VALUES ('Repel','Miscellaneous','Prevents wild Pokemon from attacking');
INSERT INTO item VALUES ('Revive','Recovery','Revives fainted Pokemon');
INSERT INTO item VALUES ('S.S. Ticket','Key','Used to Board S.S. Anne');
INSERT INTO item VALUES ('Safari Ball','Ball','Used in Safari Zone');
INSERT INTO item VALUES ('Secret Key','Key','Unlocks Cinnabar Island Gym');
INSERT INTO item VALUES ('Silph Scope','Key','Used to identify Ghosts');
INSERT INTO item VALUES ('Soda Pop','Recovery','Quenches Thirsts Restores 60 HP');
INSERT INTO item VALUES ('Super Potion','Recovery','Restores 50 HP');
INSERT INTO item VALUES ('Super Repel','Miscellaneous','Prevents wild Pokemon from attacking');
INSERT INTO item VALUES ('Super Rod','Key','Fishes for Pokemon');
INSERT INTO item VALUES ('Thunder Stone','Stone','Evolves some Electric Pokemon');
INSERT INTO item VALUES ('Town Map','Key','Shows you where you are');
INSERT INTO item VALUES ('Ultra Ball','Ball','Better than Great Balls');
INSERT INTO item VALUES ('Water Stone','Stone','Evolves some water Pokemon');
INSERT INTO item VALUES ('X Accuracy','Battle','Boosts Accuracy Temporarily');
INSERT INTO item VALUES ('X Attack','Battle','Boosts Attack Temporarily');
INSERT INTO item VALUES ('X Defend','Battle','Boosts Defense Temporarily');
INSERT INTO item VALUES ('X Special','Battle','Boosts Special Temporarily');
INSERT INTO item VALUES ('X Speed','Battle','Boosts Speed Temporarily');
INSERT INTO item VALUES ('TM01','Technical Machine','Mega Punch');
INSERT INTO item VALUES ('TM02','Technical Machine','Razor Wind');
INSERT INTO item VALUES ('TM03','Technical Machine','Swords Dance');
INSERT INTO item VALUES ('TM04','Technical Machine','Whirlwind');
INSERT INTO item VALUES ('TM05','Technical Machine','Mega Kick');
INSERT INTO item VALUES ('TM06','Technical Machine','Toxic');
INSERT INTO item VALUES ('TM07','Technical Machine','Horn Drill');
INSERT INTO item VALUES ('TM08','Technical Machine','Body Slam');
INSERT INTO item VALUES ('TM09','Technical Machine','Take Down');
INSERT INTO item VALUES ('TM10','Technical Machine','Double Edge');
INSERT INTO item VALUES ('TM11','Technical Machine','Bubble Beam');
INSERT INTO item VALUES ('TM12','Technical Machine','Water Gun');
INSERT INTO item VALUES ('TM13','Technical Machine','Ice Beam');
INSERT INTO item VALUES ('TM14','Technical Machine','Blizzard');
INSERT INTO item VALUES ('TM15','Technical Machine','Hyper Beam');
INSERT INTO item VALUES ('TM16','Technical Machine','Pay Day');
INSERT INTO item VALUES ('TM17','Technical Machine','Submission');
INSERT INTO item VALUES ('TM18','Technical Machine','Counter');
INSERT INTO item VALUES ('TM19','Technical Machine','Seismic Toss');
INSERT INTO item VALUES ('TM20','Technical Machine','Rage');
INSERT INTO item VALUES ('TM21','Technical Machine','Mega Drain');
INSERT INTO item VALUES ('TM22','Technical Machine','Solar Beam');
INSERT INTO item VALUES ('TM23','Technical Machine','Dragon Rage');
INSERT INTO item VALUES ('TM24','Technical Machine','Thunderbolt');
INSERT INTO item VALUES ('TM25','Technical Machine','Thunder');
INSERT INTO item VALUES ('TM26','Technical Machine','Earthquake');
INSERT INTO item VALUES ('TM27','Technical Machine','Fissure');
INSERT INTO item VALUES ('TM28','Technical Machine','Dig');
INSERT INTO item VALUES ('TM29','Technical Machine','Psychic');
INSERT INTO item VALUES ('TM30','Technical Machine','Teleport');
INSERT INTO item VALUES ('TM31','Technical Machine','Mimic');
INSERT INTO item VALUES ('TM32','Technical Machine','Double Team');
INSERT INTO item VALUES ('TM33','Technical Machine','Reflect');
INSERT INTO item VALUES ('TM34','Technical Machine','Bide');
INSERT INTO item VALUES ('TM35','Technical Machine','Metronome');
INSERT INTO item VALUES ('TM36','Technical Machine','Self Destruct');
INSERT INTO item VALUES ('TM37','Technical Machine','Egg Bomb');
INSERT INTO item VALUES ('TM38','Technical Machine','Fire Blast');
INSERT INTO item VALUES ('TM39','Technical Machine','Swift');
INSERT INTO item VALUES ('TM40','Technical Machine','Skull Bash');
INSERT INTO item VALUES ('TM41','Technical Machine','Soft Boiled');
INSERT INTO item VALUES ('TM42','Technical Machine','Dream Eater');
INSERT INTO item VALUES ('TM43','Technical Machine','Sky Attack');
INSERT INTO item VALUES ('TM44','Technical Machine','Rest');
INSERT INTO item VALUES ('TM45','Technical Machine','Thunder Wave');
INSERT INTO item VALUES ('TM46','Technical Machine','Psywave');
INSERT INTO item VALUES ('TM47','Technical Machine','Explosion');
INSERT INTO item VALUES ('TM48','Technical Machine','Rock Slide');
INSERT INTO item VALUES ('TM49','Technical Machine','Tri Attack');
INSERT INTO item VALUES ('TM50','Technical Machine','Substitute');
INSERT INTO item VALUES ('HM01','Hidden Machine','Cut');
INSERT INTO item VALUES ('HM02','Hidden Machine','Fly');
INSERT INTO item VALUES ('HM03','Hidden Machine','Surf');
INSERT INTO item VALUES ('HM04','Hidden Machine','Strength');
INSERT INTO item VALUES ('HM05','Hidden Machine','Flash');
