INSERT INTO live VALUES ('TID','LName');
INSERT INTO live VALUES ('Rival_1','Prof. Oak Lab');
INSERT INTO live VALUES ('Bug Catcher Rick','Viridian Forest');
INSERT INTO live VALUES ('Bug Catcher Doug','Viridian Forest');
INSERT INTO live VALUES ('Bug Catcher Anthony','Viridian Forest');
INSERT INTO live VALUES ('Bug Catcher Charlie','Viridian Forest');
INSERT INTO live VALUES ('Bug Catcher Sammy','Viridian Forest');
INSERT INTO live VALUES ('Camper Liam','Pewter City Gym');
INSERT INTO live VALUES ('Leader Brock','Pewter City Gym');
INSERT INTO live VALUES ('Lass Janice','Route 3');
INSERT INTO live VALUES ('Bug Catcher Colton','Route 3');
INSERT INTO live VALUES ('Youngster Ben','Route 3');
INSERT INTO live VALUES ('Bug Catcher Greg','Route 3');
INSERT INTO live VALUES ('Lass Sally','Route 3');
INSERT INTO live VALUES ('Bug Catcher James','Route 3');
INSERT INTO live VALUES ('Youngster Calvin','Route 3');
INSERT INTO live VALUES ('Lass Robin','Route 3');
INSERT INTO live VALUES ('Lass Iris','Mt. Moon');
INSERT INTO live VALUES ('Bug Catcher Kent','Mt. Moon');
INSERT INTO live VALUES ('Super Nerd Jovan','Mt. Moon');
INSERT INTO live VALUES ('Bug Catcher Robby','Mt. Moon');
INSERT INTO live VALUES ('Lass Miriam','Mt. Moon');
INSERT INTO live VALUES ('Team Rocket Grunt_1','Mt. Moon');
INSERT INTO live VALUES ('Team Rocket Grunt_2','Mt. Moon');
INSERT INTO live VALUES ('Youngster Josh','Mt. Moon');
INSERT INTO live VALUES ('Hiker Marcos','Mt. Moon');
INSERT INTO live VALUES ('Team Rocket Grunt_3','Mt. Moon');
INSERT INTO live VALUES ('Team Rocket Grunt_4','Mt. Moon');
INSERT INTO live VALUES ('Super Nerd Miguel','Mt. Moon');
INSERT INTO live VALUES ('Lass Crissy','Route 4');
INSERT INTO live VALUES ('Rival_2','Route 24');
INSERT INTO live VALUES ('Bug Catcher Cale','Route 24');
INSERT INTO live VALUES ('Lass Ali','Route 24');
INSERT INTO live VALUES ('Youngster Timmy','Route 24');
INSERT INTO live VALUES ('Lass Reli','Route 24');
INSERT INTO live VALUES ('Camper Ethan','Route 24');
INSERT INTO live VALUES ('Team Rocket Grunt_5','Route 24');
INSERT INTO live VALUES ('Camper Shane','Route 24');
INSERT INTO live VALUES ('Hiker Franklin','Route 25');
INSERT INTO live VALUES ('Hiker Wayne','Route 25');
INSERT INTO live VALUES ('Youngster Joey','Route 25');
INSERT INTO live VALUES ('Youngester Dan','Route 25');
INSERT INTO live VALUES ('Picnicker Kelsey','Route 25');
INSERT INTO live VALUES ('Hiker Nob','Route 25');
INSERT INTO live VALUES ('Camper Flint','Route 25');
INSERT INTO live VALUES ('Youngster Chad','Route 25');
INSERT INTO live VALUES ('Lass Haley','Route 25');
INSERT INTO live VALUES ('Swimmer Luis','Cerulean City Gym');
INSERT INTO live VALUES ('Picnicker Diana','Cerulean City Gym');
INSERT INTO live VALUES ('Leader Misty','Cerulean City Gym');
INSERT INTO live VALUES ('Team Rocket Grunt_6','Cerulean City');
INSERT INTO live VALUES ('Bug Catcher Keigo','Route 6');
INSERT INTO live VALUES ('Camper Ricky','Route 6');
INSERT INTO live VALUES ('Picnicker Nancy','Route 6');
INSERT INTO live VALUES ('Bug Catcher Elijah','Route 6');
INSERT INTO live VALUES ('Picnicker Isabelle','Route 6');
INSERT INTO live VALUES ('Camper Jeff','Route 6');
INSERT INTO live VALUES ('Youngster Eddie','Route 11');
INSERT INTO live VALUES ('Gamer Hugo','Route 11');
INSERT INTO live VALUES ('Engineer Bernie','Route 11');
INSERT INTO live VALUES ('Gamer Jasper','Route 11');
INSERT INTO live VALUES ('Youngster Dave','Route 11');
INSERT INTO live VALUES ('Youngster Dillon','Route 11');
INSERT INTO live VALUES ('Engineer Braxton','Route 11');
INSERT INTO live VALUES ('Youngster Yasu','Route 11');
INSERT INTO live VALUES ('Gamer Darian','Route 11');
INSERT INTO live VALUES ('Gamer Dirk','Route 11');
INSERT INTO live VALUES ('Fisherman Barny','S. S. Anne');
INSERT INTO live VALUES ('Sailer Phillip','S. S. Anne');
INSERT INTO live VALUES ('Sailer Huey','S. S. Anne');
INSERT INTO live VALUES ('Sailor Dylan','S. S. Anne');
INSERT INTO live VALUES ('Sailor Duncan','S. S. Anne');
INSERT INTO live VALUES ('Sailor leonard','S. S. Anne');
INSERT INTO live VALUES ('Gentleman Thomas','S. S. Anne');
INSERT INTO live VALUES ('Gentleman Arthur','S. S. Anne');
INSERT INTO live VALUES ('Lass Ann','S. S. Anne');
INSERT INTO live VALUES ('Youngster Tyler','S. S. Anne');
INSERT INTO live VALUES ('Sailor Trevor','S. S. Anne');
INSERT INTO live VALUES ('Sailor Edmond','S. S. Anne');
INSERT INTO live VALUES ('Fisherman Dale','S. S. Anne');
INSERT INTO live VALUES ('Gentleman Brooks','S. S. Anne');
INSERT INTO live VALUES ('Lass Dawn','S. S. Anne');
INSERT INTO live VALUES ('Gentleman Lamar','S. S. Anne');
INSERT INTO live VALUES ('Rival_3','S. S. Anne');
INSERT INTO live VALUES ('Sailor Dwayne','Vermilion CityGym');
INSERT INTO live VALUES ('Engineer Baily','Vermilion CityGym');
INSERT INTO live VALUES ('Gentleman Tucker','Vermilion CityGym');
INSERT INTO live VALUES ('Leader Lt. Surge','Vermilion CityGym');
INSERT INTO live VALUES ('Picnicker Alicia','Route 9');
INSERT INTO live VALUES ('Hiker Jeremy','Route 9');
INSERT INTO live VALUES ('Camper Chris','Route 9');
INSERT INTO live VALUES ('Bug Catcher Brent','Route 9');
INSERT INTO live VALUES ('Bug Catcher Conner','Route 9');
INSERT INTO live VALUES ('Bug Camper Drew','Route 9');
INSERT INTO live VALUES ('Hiker Alan','Route 9');
INSERT INTO live VALUES ('Hiker Brice','Route 9');
INSERT INTO live VALUES ('Picnicker Caitlin','Route 9');
INSERT INTO live VALUES ('Picnicker Heidi','Route 10');
INSERT INTO live VALUES ('Picnicker Carol','Route 10');
INSERT INTO live VALUES ('Hiker Clark','Route 10');
INSERT INTO live VALUES ('Hiker Trent','Route 10');
INSERT INTO live VALUES ('Pokemaniac Herman','Route 10');
INSERT INTO live VALUES ('Pokemaniac Mark','Route 10');
INSERT INTO live VALUES ('Pokemaniac Ashton','Rock Tunnel');
INSERT INTO live VALUES ('Pokemaniac Winston','Rock Tunnel');
INSERT INTO live VALUES ('Picnicker Martha','Rock Tunnel');
INSERT INTO live VALUES ('Pokemaniac Steve','Rock Tunnel');
INSERT INTO live VALUES ('Hiker Allen','Rock Tunnel');
INSERT INTO live VALUES ('Hiker Eric','Rock Tunnel');
INSERT INTO live VALUES ('Hiker Lenny','Rock Tunnel');
INSERT INTO live VALUES ('Hiker Oliver','Rock Tunnel');
INSERT INTO live VALUES ('Hiker Lucas','Rock Tunnel');
INSERT INTO live VALUES ('Picnicker Sofia','Rock Tunnel');
INSERT INTO live VALUES ('Hiker Dudley','Rock Tunnel');
INSERT INTO live VALUES ('Pokemaniac Cooper','Rock Tunnel');
INSERT INTO live VALUES ('Picnicker Leah','Rock Tunnel');
INSERT INTO live VALUES ('Picnicker Arianna','Rock Tunnel');
INSERT INTO live VALUES ('Picnicker Dana','Rock Tunnel');
INSERT INTO live VALUES ('Lass Julia','Route 8');
INSERT INTO live VALUES ('Gamer Rich','Route 8');
INSERT INTO live VALUES ('Super Nerd Glenn','Route 8');
INSERT INTO live VALUES ('Lass Megan','Route 8');
INSERT INTO live VALUES ('Lass Andrea','Route 8');
INSERT INTO live VALUES ('Super Nerd Leslie','Route 8');
INSERT INTO live VALUES ('Lass Paige','Route 8');
INSERT INTO live VALUES ('Biker Jaren','Route 8');
INSERT INTO live VALUES ('Biker Ricardo','Route 8');
INSERT INTO live VALUES ('Super Nerd Aiden','Route 8');
INSERT INTO live VALUES ('Gamer Stan','Route 8');
INSERT INTO live VALUES ('Lass Kay','Celadon City Gym');
INSERT INTO live VALUES ('Beauty Bridget','Celadon City Gym');
INSERT INTO live VALUES ('Picnicker Tina','Celadon City Gym');
INSERT INTO live VALUES ('Beauty Tamia','Celadon City Gym');
INSERT INTO live VALUES ('Beauty Lori','Celadon City Gym');
INSERT INTO live VALUES ('Lass Lisa','Celadon City Gym');
INSERT INTO live VALUES ('Cooltrainer Mary','Celadon City Gym');
INSERT INTO live VALUES ('Leader Erika','Celadon City Gym');
INSERT INTO live VALUES ('Team Rocket Grunt_7','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_8','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_9','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_10','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_11','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_12','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_13','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_14','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_15','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_16','Casino');
INSERT INTO live VALUES ('Team Rocket Grunt_17','Casino');
INSERT INTO live VALUES ('Boss Giovanni_1','Casino');
INSERT INTO live VALUES ('Rival_6','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Hope','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Patricia','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Carly','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Laurel','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Jody','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Paula','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Ruth','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Tammy','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Karina','Pokemon Tower');
INSERT INTO live VALUES ('Channeler janae','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Angelica','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Jennifer','Pokemon Tower');
INSERT INTO live VALUES ('Channeler Emilia','Pokemon Tower');
INSERT INTO live VALUES ('Team Rocket Grunt_18','Pokemon Tower');
INSERT INTO live VALUES ('Team Rocket Grunt_19','Pokemon Tower');
INSERT INTO live VALUES ('Team Rocket Grunt_20','Pokemon Tower');
INSERT INTO live VALUES ('Biker Lao','Route 16');
INSERT INTO live VALUES ('Cue Ball Luke','Route 16');
INSERT INTO live VALUES ('Cue Ball Koji','Route 16');
INSERT INTO live VALUES ('Biker Hideo','Route 16');
INSERT INTO live VALUES ('Biker Ruben','Route 16');
INSERT INTO live VALUES ('Cue Ball Camron','Route 16');
INSERT INTO live VALUES ('Cue Ball Isaiah','Route 17');
INSERT INTO live VALUES ('Biker Virgil','Route 17');
INSERT INTO live VALUES ('Cue Ball Raul','Route 17');
INSERT INTO live VALUES ('Biker Billy','Route 17');
INSERT INTO live VALUES ('Biker Nikolas','Route 17');
INSERT INTO live VALUES ('Cue Ball Zeek','Route 17');
INSERT INTO live VALUES ('Cue Ball Corey','Route 17');
INSERT INTO live VALUES ('Biker Jaxon','Route 17');
INSERT INTO live VALUES ('Cue Ball Jamal','Route 17');
INSERT INTO live VALUES ('Biker William','Route 17');
INSERT INTO live VALUES ('Bird Keeper Jacob','Route 18');
INSERT INTO live VALUES ('Bird Keeper Wilton','Route 18');
INSERT INTO live VALUES ('Bird Keeper Ramiro','Route 18');
INSERT INTO live VALUES ('Juggler Nate','Fuchsia City Gym');
INSERT INTO live VALUES ('Juggler Kayden','Fuchsia City Gym');
INSERT INTO live VALUES ('Juggler Kirk','Fuchsia City Gym');
INSERT INTO live VALUES ('Tamer Edgar','Fuchsia City Gym');
INSERT INTO live VALUES ('Tamer Phil','Fuchsia City Gym');
INSERT INTO live VALUES ('Juggler Shawn','Fuchsia City Gym');
INSERT INTO live VALUES ('Leader Koga','Fuchsia City Gym');
INSERT INTO live VALUES ('Black Belt Hitoshi','Fighting Dojo');
INSERT INTO live VALUES ('Black Belt Hideki','Fighting Dojo');
INSERT INTO live VALUES ('Black Belt Aaron','Fighting Dojo');
INSERT INTO live VALUES ('Black Belt Mike','Fighting Dojo');
INSERT INTO live VALUES ('Black Belt Koichi','Fighting Dojo');
INSERT INTO live VALUES ('Team Rocket Grunt_21','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_22','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_23','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_24','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_25','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_26','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_27','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_28','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_29','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_30','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_31','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_32','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_33','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_34','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_35','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_36','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_37','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_38','Silph Co. Building');
INSERT INTO live VALUES ('Team Rocket Grunt_39','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Jerry','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Jose','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Rodney','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Beau','Silph Co. Building');
INSERT INTO live VALUES ('Juggler Dalton','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Taylor','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Joshua','Silph Co. Building');
INSERT INTO live VALUES ('Rival_4','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Parker','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Ed','Silph Co. Building');
INSERT INTO live VALUES ('Scientist Travis','Silph Co. Building');
INSERT INTO live VALUES ('Boss Giovanni_2','Silph Co. Building');
INSERT INTO live VALUES ('Psychic Cameron','Saffron City Gym');
INSERT INTO live VALUES ('Channeler Tasha','Saffron City Gym');
INSERT INTO live VALUES ('Psychic Johan','Saffron City Gym');
INSERT INTO live VALUES ('Psychic Tyron','Saffron City Gym');
INSERT INTO live VALUES ('Channeler Stacy','Saffron City Gym');
INSERT INTO live VALUES ('Channeler Amanda','Saffron City Gym');
INSERT INTO live VALUES ('Psychic Preston','Saffron City Gym');
INSERT INTO live VALUES ('Leader Sabrina','Saffron City Gym');
INSERT INTO live VALUES ('Fisherman Ned','Route 12');
INSERT INTO live VALUES ('Fisherman Chip','Route 12');
INSERT INTO live VALUES ('Fisherman Hank','Route 12');
INSERT INTO live VALUES ('Fisherman Elliot','Route 12');
INSERT INTO live VALUES ('Rocker Luca','Route 12');
INSERT INTO live VALUES ('Camper Justin','Route 12');
INSERT INTO live VALUES ('Fisherman Andrew','Route 12');
INSERT INTO live VALUES ('Picnicker Alma','Route 13');
INSERT INTO live VALUES ('Bird Keeper Sebastian','Route 13');
INSERT INTO live VALUES ('Picnicker Susie','Route 13');
INSERT INTO live VALUES ('Beauty Lola','Route 13');
INSERT INTO live VALUES ('Beauty Sheila','Route 13');
INSERT INTO live VALUES ('Picnicker Valerie','Route 13');
INSERT INTO live VALUES ('Picnicker Gwen','Route 13');
INSERT INTO live VALUES ('Bird Keeper Perry','Route 13');
INSERT INTO live VALUES ('Biker Jared','Route 13');
INSERT INTO live VALUES ('Bird Keeper Robert','Route 13');
INSERT INTO live VALUES ('Bird Keeper Carter','Route 14');
INSERT INTO live VALUES ('Bird Keeper Mitch','Route 14');
INSERT INTO live VALUES ('Bird Keeper Marlon','Route 14');
INSERT INTO live VALUES ('Bird Keeper Beck','Route 14');
INSERT INTO live VALUES ('Bird Keeper Donald','Route 14');
INSERT INTO live VALUES ('Bird Keeper Benny','Route 14');
INSERT INTO live VALUES ('Biker Geralk','Route 14');
INSERT INTO live VALUES ('Biker Malik','Route 14');
INSERT INTO live VALUES ('Biker Isaac','Route 14');
INSERT INTO live VALUES ('Biker Lukas','Route 14');
INSERT INTO live VALUES ('Picnicker Becky','Route 15');
INSERT INTO live VALUES ('Picnicker Celia','Route 15');
INSERT INTO live VALUES ('Biker Ernest','Route 15');
INSERT INTO live VALUES ('Biker Alex','Route 15');
INSERT INTO live VALUES ('Beauty Grace','Route 15');
INSERT INTO live VALUES ('Beauty Olivia','Route 15');
INSERT INTO live VALUES ('Picnicker Kindra','Route 15');
INSERT INTO live VALUES ('Bird Keeper Chester','Route 15');
INSERT INTO live VALUES ('Bird Keeper Edwin','Route 15');
INSERT INTO live VALUES ('Picnicker Yazmin','Route 15');
INSERT INTO live VALUES ('Swimmer (M) Richard','Route 19');
INSERT INTO live VALUES ('Swimer (M) Reece','Route 19');
INSERT INTO live VALUES ('Swimmer (M) Tony','Route 19');
INSERT INTO live VALUES ('Swimmer (M) David','Route 19');
INSERT INTO live VALUES ('Swimmer (M) Douglas','Route 19');
INSERT INTO live VALUES ('Swimmer (M) Matthew','Route 19');
INSERT INTO live VALUES ('Swimmer (M) Axle','Route 19');
INSERT INTO live VALUES ('Swimmer (F) Alice','Route 19');
INSERT INTO live VALUES ('Swimmer (F) Connie','Route 19');
INSERT INTO live VALUES ('Swimmer (F) Anya','Route 19');
INSERT INTO live VALUES ('Swimmer (M) Barry','Route 20');
INSERT INTO live VALUES ('Swimmer (M) Darrin','Route 20');
INSERT INTO live VALUES ('Swimmer (F) Shirley','Route 20');
INSERT INTO live VALUES ('Swimmer (F) Tiffany','Route 20');
INSERT INTO live VALUES ('Picnicker Irene','Route 20');
INSERT INTO live VALUES ('Bird Keeper Roger','Route 20');
INSERT INTO live VALUES ('Swimmer (F) Nora','Route 20');
INSERT INTO live VALUES ('Swimmer (M) Dean','Route 20');
INSERT INTO live VALUES ('Picnicker Missy','Route 20');
INSERT INTO live VALUES ('Swimmer (F) Melissa','Route 20');
INSERT INTO live VALUES ('Youngster Johnson','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Scientist Ted','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Burglar Arnie','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Burglar Simon','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Scientist Braydon','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Burglar Lewis','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Scientist Ivan','Cinnibar Island Mansion');
INSERT INTO live VALUES ('Burglar Quinn','Cinnabar Island Gym');
INSERT INTO live VALUES ('Super Nerd Erik','Cinnabar Island Gym');
INSERT INTO live VALUES ('Super Nerd Avery','Cinnabar Island Gym');
INSERT INTO live VALUES ('Burglar Ramon','Cinnabar Island Gym');
INSERT INTO live VALUES ('Super Nerd Derek','Cinnabar Island Gym');
INSERT INTO live VALUES ('Burglar Dusty','Cinnabar Island Gym');
INSERT INTO live VALUES ('Super Nerd Zac','Cinnabar Island Gym');
INSERT INTO live VALUES ('Leader Blaine','Cinnabar Island Gym');
INSERT INTO live VALUES ('Fisherman Wade','Route 21');
INSERT INTO live VALUES ('Fisherman Ronald','Route 21');
INSERT INTO live VALUES ('Swimmer (M) Spencer','Route 21');
INSERT INTO live VALUES ('Fisherman Claude','Route 21');
INSERT INTO live VALUES ('Fisherman Nolan','Route 21');
INSERT INTO live VALUES ('Swimmer (M) Jack','Route 21');
INSERT INTO live VALUES ('Swimmer (M) Roland','Route 21');
INSERT INTO live VALUES ('Swimmer (M) Jerome','Route 21');
INSERT INTO live VALUES ('Tamer Cole','Viridian City Gym');
INSERT INTO live VALUES ('Black Belt Kiyo','Viridian City Gym');
INSERT INTO live VALUES ('Cool Trainer Samuel','Viridian City Gym');
INSERT INTO live VALUES ('Cool Trainer Yuji','Viridian City Gym');
INSERT INTO live VALUES ('Black Belt Atsushi','Viridian City Gym');
INSERT INTO live VALUES ('Tamer Jason','Viridian City Gym');
INSERT INTO live VALUES ('Cool Trainer Warren','Viridian City Gym');
INSERT INTO live VALUES ('Black Belt Takashi','Viridian City Gym');
INSERT INTO live VALUES ('Leader Giovanni','Viridian City Gym');
INSERT INTO live VALUES ('Rival_5','Route 22');
INSERT INTO live VALUES ('Cool Trainer Naomi','Victory Road');
INSERT INTO live VALUES ('Cool Trainer Rolando','Victory Road');
INSERT INTO live VALUES ('Black Belt Daisuke','Victory Road');
INSERT INTO live VALUES ('Juggler Nelson','Victory Road');
INSERT INTO live VALUES ('Tamer Vincent','Victory Road');
INSERT INTO live VALUES ('Juggler Gregory','Victory Road');
INSERT INTO live VALUES ('Cool Trainer George','Victory Road');
INSERT INTO live VALUES ('Pokemanic Dawson','Victory Road');
INSERT INTO live VALUES ('Cool Trainer Alexa','Victory Road');
INSERT INTO live VALUES ('Cool Trainer Colby','Victory Road');
INSERT INTO live VALUES ('Cool Trainer Caroline','Victory Road');
INSERT INTO live VALUES ('Cool Couple Ray','Victory Road');
INSERT INTO live VALUES ('Elite Four Lorelei','Indigo Plateau');
INSERT INTO live VALUES ('Elite Four Bruno','Indigo Plateau');
INSERT INTO live VALUES ('Elite Four Agatha','Indigo Plateau');
INSERT INTO live VALUES ('Elite Four Lance','Indigo Plateau');
INSERT INTO live VALUES ('Champion Rival','Indigo Plateau');
