INSERT INTO poke_found VALUES ('1','Prof. Oak Lab');
INSERT INTO poke_found VALUES ('2','Evolved from Bulbasaur');
INSERT INTO poke_found VALUES ('3','Evolve from Ivysaur');
INSERT INTO poke_found VALUES ('4','Prof. Oak Lab');
INSERT INTO poke_found VALUES ('5','Evolved from Charmander');
INSERT INTO poke_found VALUES ('6','Evolved from Charmeleon');
INSERT INTO poke_found VALUES ('7','Prof. Oak Lab');
INSERT INTO poke_found VALUES ('8','Evolved from Squirtle');
INSERT INTO poke_found VALUES ('9','Evolved from Wartortle');
INSERT INTO poke_found VALUES ('10','Viridian Forest');
INSERT INTO poke_found VALUES ('11','Viridian Forest');
INSERT INTO poke_found VALUES ('12','Evolved from Metapod');
INSERT INTO poke_found VALUES ('13','Viridian Forest');
INSERT INTO poke_found VALUES ('14','Viridian Forest');
INSERT INTO poke_found VALUES ('15','Evolved from Kakuna');
INSERT INTO poke_found VALUES ('16','Route 1);
INSERT INTO poke_found VALUES ('17','Route 21');
INSERT INTO poke_found VALUES ('18','Evolved from Pidgeotto');
INSERT INTO poke_found VALUES ('19','Route 1');
INSERT INTO poke_found VALUES ('20','Route 16');
INSERT INTO poke_found VALUES ('21','Routes 3');
INSERT INTO poke_found VALUES ('22','Route 17');
INSERT INTO poke_found VALUES ('23','Routes 4');
INSERT INTO poke_found VALUES ('24','Route 23');
INSERT INTO poke_found VALUES ('25','Viridian Forest');
INSERT INTO poke_found VALUES ('26','Route 23');
INSERT INTO poke_found VALUES ('27','Route 4');
INSERT INTO poke_found VALUES ('28','Route 23');
INSERT INTO poke_found VALUES ('29','Route 22');
INSERT INTO poke_found VALUES ('30','Safari Zone');
INSERT INTO poke_found VALUES ('31','Evolved from Nidorina');
INSERT INTO poke_found VALUES ('32','Route 22');
INSERT INTO poke_found VALUES ('33','Safari Zone');
INSERT INTO poke_found VALUES ('34','Evolved from Nidorino');
INSERT INTO poke_found VALUES ('35','Mt. Moon');
INSERT INTO poke_found VALUES ('36','Evolved from Clefairy');
INSERT INTO poke_found VALUES ('37','Pokemon Mansion');
INSERT INTO poke_found VALUES ('38','Evolved from Vulpix');
INSERT INTO poke_found VALUES ('39','Route 3');
INSERT INTO poke_found VALUES ('40','Cerulean Cave');
INSERT INTO poke_found VALUES ('41','Mt. Moon');
INSERT INTO poke_found VALUES ('42','Route 23');
INSERT INTO poke_found VALUES ('43','Route 12');
INSERT INTO poke_found VALUES ('44','Route 15');
INSERT INTO poke_found VALUES ('45','Evolved from Gloom');
INSERT INTO poke_found VALUES ('46','Mt. Moon');
INSERT INTO poke_found VALUES ('47','Safari Zone');
INSERT INTO poke_found VALUES ('48','Route 15');
INSERT INTO poke_found VALUES ('49','Victory Road');
INSERT INTO poke_found VALUES ('50','Diglett Cave');
INSERT INTO poke_found VALUES ('51','Diglett Cave');
INSERT INTO poke_found VALUES ('52','Route 8');
INSERT INTO poke_found VALUES ('53','Evolved from Meowth');
INSERT INTO poke_found VALUES ('54','Route 24');
INSERT INTO poke_found VALUES ('55','Seafoam Islands');
INSERT INTO poke_found VALUES ('56','Route 8');
INSERT INTO poke_found VALUES ('57','Evolved from Mankey');
INSERT INTO poke_found VALUES ('58','Route 7');
INSERT INTO poke_found VALUES ('59','Evolved from Growlithe');
INSERT INTO poke_found VALUES ('60','Pallet Town');
INSERT INTO poke_found VALUES ('61','Route 10');
INSERT INTO poke_found VALUES ('62','Evolved from Poliwhirl');
INSERT INTO poke_found VALUES ('63','Celedon City');
INSERT INTO poke_found VALUES ('64','Cerulean Cave');
INSERT INTO poke_found VALUES ('65','Evolved from Kadabra');
INSERT INTO poke_found VALUES ('66','Victory Road');
INSERT INTO poke_found VALUES ('67','Victory Road');
INSERT INTO poke_found VALUES ('68','Evolved from Machoke');
INSERT INTO poke_found VALUES ('69','Route 5');
INSERT INTO poke_found VALUES ('70','Route 12');
INSERT INTO poke_found VALUES ('71','Evolved from Weepinbell');
INSERT INTO poke_found VALUES ('72','Pallet Town');
INSERT INTO poke_found VALUES ('73','Evolved from Tentacool');
INSERT INTO poke_found VALUES ('74','Mt. Moon');
INSERT INTO poke_found VALUES ('75','Victory Road');
INSERT INTO poke_found VALUES ('76','Evolved from Graveler');
INSERT INTO poke_found VALUES ('77','Pokemon Mansion');
INSERT INTO poke_found VALUES ('78','Evolved from Ponyta');
INSERT INTO poke_found VALUES ('79','Route 10');
INSERT INTO poke_found VALUES ('80','Route 23');
INSERT INTO poke_found VALUES ('81','Cerulean Cave');
INSERT INTO poke_found VALUES ('82','Cerulean Cave');
INSERT INTO poke_found VALUES ('83','Vermilion City');
INSERT INTO poke_found VALUES ('84','Route 16');
INSERT INTO poke_found VALUES ('85','Cerulean Cave');
INSERT INTO poke_found VALUES ('86','Seafoam Islands');
INSERT INTO poke_found VALUES ('87','Seafoam Islands');
INSERT INTO poke_found VALUES ('88','Pokemon Mansion');
INSERT INTO poke_found VALUES ('89','Cerulean Cave');
INSERT INTO poke_found VALUES ('90','Route 6');
INSERT INTO poke_found VALUES ('91','Evolved from Shellder');
INSERT INTO poke_found VALUES ('92','Pokemon Tower');
INSERT INTO poke_found VALUES ('93','Pokemon Tower');
INSERT INTO poke_found VALUES ('94','Evolved from Haunter');
INSERT INTO poke_found VALUES ('95','Victory Road');
INSERT INTO poke_found VALUES ('96','Route 11');
INSERT INTO poke_found VALUES ('97','Cerulean Cave');
INSERT INTO poke_found VALUES ('98','Route 4');
INSERT INTO poke_found VALUES ('99','Route 23');
INSERT INTO poke_found VALUES ('100','Power Plant');
INSERT INTO poke_found VALUES ('101','Cerulean Cave');
INSERT INTO poke_found VALUES ('102','Safari Zone');
INSERT INTO poke_found VALUES ('103','Evolved from Exeggcute');
INSERT INTO poke_found VALUES ('104','Pokemon Tower');
INSERT INTO poke_found VALUES ('105','Victory Road');
INSERT INTO poke_found VALUES ('106','Saffron City');
INSERT INTO poke_found VALUES ('107','Saffron City');
INSERT INTO poke_found VALUES ('108','Route 18');
INSERT INTO poke_found VALUES ('109','Pokemon Mansion');
INSERT INTO poke_found VALUES ('110','Pokemon Mansion');
INSERT INTO poke_found VALUES ('111','Safari Zone');
INSERT INTO poke_found VALUES ('112','Cerulean Cave');
INSERT INTO poke_found VALUES ('113','Safari Zone');
INSERT INTO poke_found VALUES ('114','Route 21');
INSERT INTO poke_found VALUES ('115','Safari Zone');
INSERT INTO poke_found VALUES ('116','Route 19');
INSERT INTO poke_found VALUES ('117','Route 23');
INSERT INTO poke_found VALUES ('118','Pallet Town');
INSERT INTO poke_found VALUES ('119','Route 23');
INSERT INTO poke_found VALUES ('120','Route 19');
INSERT INTO poke_found VALUES ('121','Evolved from Staryu');
INSERT INTO poke_found VALUES ('122','Viridian City');
INSERT INTO poke_found VALUES ('123','Celedon City');
INSERT INTO poke_found VALUES ('124','Cerulean City');
INSERT INTO poke_found VALUES ('125','Power Plant');
INSERT INTO poke_found VALUES ('126','Pokemon Mansion');
INSERT INTO poke_found VALUES ('127','Celedon City');
INSERT INTO poke_found VALUES ('128','Safari Zone');
INSERT INTO poke_found VALUES ('129','Pallet Town');
INSERT INTO poke_found VALUES ('130','Evolved from Magikarp');
INSERT INTO poke_found VALUES ('131','Silph Co.');
INSERT INTO poke_found VALUES ('132','Route 13');
INSERT INTO poke_found VALUES ('133','Celedon City');
INSERT INTO poke_found VALUES ('134','Evolved from Eevee');
INSERT INTO poke_found VALUES ('135','Evolved from Eevee');
INSERT INTO poke_found VALUES ('136','Evolved from Eevee');
INSERT INTO poke_found VALUES ('137','Celedon City');
INSERT INTO poke_found VALUES ('138','Cinnabar Island');
INSERT INTO poke_found VALUES ('139','Evolved from Omanyte');
INSERT INTO poke_found VALUES ('140','Cinnabar Island');
INSERT INTO poke_found VALUES ('141','Evolved from Kabuto');
INSERT INTO poke_found VALUES ('142','Cinnabar Island');
INSERT INTO poke_found VALUES ('143','Route 12');
INSERT INTO poke_found VALUES ('144','Seafoam Islands');
INSERT INTO poke_found VALUES ('145','Power Plant');
INSERT INTO poke_found VALUES ('146','Victory Road');
INSERT INTO poke_found VALUES ('147','Celedon City');
INSERT INTO poke_found VALUES ('148','Evolved from Dratini');
INSERT INTO poke_found VALUES ('149','Evolved from Dragonair');
INSERT INTO poke_found VALUES ('150','Cerulean Cave');
INSERT INTO poke_found VALUES ('151','S. S. Anne');
